import os
import shutil
import yaml

def move_file(src, dst):
    """Move files from src to dst."""
    attempted = False

    while True:
        try:
            shutil.move(src, dst)
        except FileNotFoundError:
            if attempted:
                return False
            os.makedirs(os.path.dirname(dst))
            attempted = True
        else:
            return os.path.exists(dst)

def load_lock_file(path: str) -> list:
    """Load the doty_lock.yml file."""
    with open(path, 'r') as f:
        lock_file = yaml.safe_load(f)
    return lock_file or []

def write_lock_file(entries: list[dict], path: str) -> None:
    """Write the doty_lock.yml file."""
    
    with open(path, 'w') as f:
        f.write('# Path: ~/.doty_config/doty_lock.yml\n')
        f.write('# This file is used to keep track of dotfiles and their respective repositories.\n')
        f.write('# It is recommended that you do not edit this file directly.\n')
        f.write('# Instead, use the \'doty add\' command.\n')
        if entries:
            yaml.safe_dump(entries, f, sort_keys=False)